//
//  PlaceDetailPresenter.swift
//  map-sample
//
//  Created by inomera on 14.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlaceDetailPresentationLogic
{
  func presentPlaceDetail(response: PlaceDetail.GetPlace.Response)
}

class PlaceDetailPresenter: PlaceDetailPresentationLogic
{
  weak var viewController: PlaceDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentPlaceDetail(response: PlaceDetail.GetPlace.Response)
  {
    let place = response.place
    let displayedPlace = PlaceDetail.GetPlace.ViewModel.DisplayedPlace(name: place.name ?? "", address: place.address ?? "")
    let viewModel = PlaceDetail.GetPlace.ViewModel(displayedPlace: displayedPlace)
    viewController?.displayMapInfo(viewModel: viewModel)
  }
}
