//
//  PlaceDetailModels.swift
//  map-sample
//
//  Created by inomera on 14.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PlaceDetail
{
  // MARK: Use cases
  
  enum GetPlace
  {
    struct Request
    {
    }
    struct Response
    {
      var place: Place
    }
    struct ViewModel
    {
      struct DisplayedPlace
      {
        var name: String
        var address: String

        struct Coordinate {
          var latitude: Double
          var longitude: Double
        }
        
        var coordinate: Coordinate

      }
      var displayedPlace: DisplayedPlace
    }
  }
}
