//
//  PlaceListWorker.swift
//  map-sample
//
//  Created by inomera on 12.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PlaceListWorker
{
  fileprivate let displayPlacesUseCase: DisplayPlacesUseCase
  
  init(displayPlacesUseCase: DisplayPlacesUseCase) {
    self.displayPlacesUseCase = displayPlacesUseCase
  }
  
  func fetchPlaces(query: String, completion: @escaping DisplayPlacesUseCaseCompletionHandler) {
    displayPlacesUseCase.displayPlaces(parameters: SearchPlaceParameters(input: query), completionHandler: completion)
  }
  
}
