//
//  PlaceListRouter.swift
//  map-sample
//
//  Created by inomera on 12.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PlaceListRoutingLogic
{
  func routeToShowOrder(indexPath: IndexPath)
}

protocol PlaceListDataPassing
{
  var dataStore: PlaceListDataStore? { get }
}

class PlaceListRouter: NSObject, PlaceListRoutingLogic, PlaceListDataPassing
{
  weak var viewController: PlaceListViewController?
  var dataStore: PlaceListDataStore?
  
  // MARK: Routing
  
  func routeToShowOrder(indexPath: IndexPath)
  {
    let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "PlaceDetailViewController") as! PlaceDetailViewController
    var destinationDS = destinationVC.router!.dataStore!
    passDataToShowOrder(source: dataStore!, destination: &destinationDS, indexPath: indexPath)
    navigateToShowOrder(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation

  func navigateToShowOrder(source: PlaceListViewController, destination: PlaceDetailViewController)
  {
    source.show(destination, sender: nil)
  }
  
  
  // MARK: Passing data
  
  func passDataToShowOrder(source: PlaceListDataStore, destination: inout PlaceDetailDataStore, indexPath: IndexPath)
  {
    destination.place = source.placeList[indexPath.row]
  }
}
