//
//  PlaceListInteractor.swift
//  map-sample
//
//  Created by inomera on 12.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlaceListBusinessLogic
{
  func fetchPlaces(request: PlaceList.PlaceModel.Request)
}

protocol PlaceListDataStore
{
  //var name: String { get set }
}

class PlaceListInteractor: PlaceListBusinessLogic, PlaceListDataStore
{
  var presenter: PlaceListPresentationLogic?
  var worker: PlaceListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func fetchPlaces(request: PlaceList.PlaceModel.Request)
  {
    worker?.doSomeWork()
    
//    let response = PlaceList.Something.Response()
//    presenter?.presentSomething(response: response)
  }
}
