//
//  PlaceListInteractor.swift
//  map-sample
//
//  Created by inomera on 12.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlaceListBusinessLogic
{
  func fetchPlaces(request: PlaceList.FetchPlaces.Request)
}

protocol PlaceListDataStore
{
  var placeList: [Place] { get set }
}

class PlaceListInteractor: PlaceListBusinessLogic, PlaceListDataStore
{
  var presenter: PlaceListPresentationLogic?
  var worker: PlaceListWorker?
  var placeList: [Place] = []
  
  // MARK: Do something
  
  func fetchPlaces(request: PlaceList.FetchPlaces.Request)
  {
    worker?.fetchPlaces(query: request.query, completion: { (result) in
      print(result)
      switch result {
      case let .success(places):
        self.placeList = places
        self.presenter?.presentPlaces(response: PlaceList.FetchPlaces.Response(places: places))
      case let .failure(error):
        // TODO: present Error Alert
        break
      }
    })
  }
}
