//
//  PlaceListPresenter.swift
//  map-sample
//
//  Created by inomera on 12.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlaceListPresentationLogic
{
  func presentSomething(response: PlaceList.Something.Response)
}

class PlaceListPresenter: PlaceListPresentationLogic
{
  weak var viewController: PlaceListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: PlaceList.Something.Response)
  {
    let viewModel = PlaceList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
