//
//  PlaceListPresenter.swift
//  map-sample
//
//  Created by inomera on 12.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlaceListPresentationLogic
{
  func presentPlaces(response: PlaceList.FetchPlaces.Response)
}

class PlaceListPresenter: PlaceListPresentationLogic
{
  weak var viewController: PlaceListDisplayLogic?
  
  // MARK: Do something
  
  func presentPlaces(response: PlaceList.FetchPlaces.Response)
  {
    let viewModel = PlaceList.FetchPlaces.ViewModel(places: response.places)
    viewController?.displayPlaces(viewModel: viewModel)
  }
}
